import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateSepsisReportPDF = (report, patientProfile) => {
  const doc = new jsPDF();
  const timestamp = new Date(report.created_at).toLocaleString();
  
  // Header
  doc.setFillColor(13, 148, 136); // brand-600 (teal)
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('SepCheck AI Medical Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${timestamp}`, 105, 30, { align: 'center' });

  // Patient Information
  doc.setTextColor(30, 41, 59); // slate-800
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient Information', 14, 55);
  
  doc.autoTable({
    startY: 60,
    head: [['Field', 'Detail']],
    body: [
      ['Full Name', patientProfile.full_name],
      ['Age / Gender', `${patientProfile.age} / ${patientProfile.gender}`],
      ['Blood Pressure', patientProfile.blood_pressure],
      ['Heart Rate', `${patientProfile.heart_rate} bpm`],
      ['Temperature', `${patientProfile.temperature} °F`],
      ['Weight / Height', `${patientProfile.weight} kg / ${patientProfile.height} cm`],
      ['Contact', patientProfile.contact_info],
    ],
    theme: 'striped',
    headStyles: { fillColor: [13, 148, 136] },
  });

  // AI Analysis Result
  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Risk Analysis', 14, finalY);
  
  const riskColor = report.risk_level === 'High' ? [225, 29, 72] : (report.risk_level === 'Medium' ? [217, 119, 6] : [5, 150, 105]);
  
  doc.autoTable({
    startY: finalY + 5,
    body: [
      ['Risk Level', report.risk_level.toUpperCase()],
      ['AI Confidence', `${(report.probability_score * 100).toFixed(1)}%`],
      ['Urgency Status', report.urgency_level],
    ],
    theme: 'grid',
    styles: { fontSize: 12, cellPadding: 5 },
    columnStyles: {
      1: { fontStyle: 'bold', textColor: riskColor }
    }
  });

  // Summary & Explanation
  const explanationY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Medical Summary & Explanation', 14, explanationY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const splitSummary = doc.splitTextToSize(report.symptoms_summary, 180);
  doc.text(splitSummary, 14, explanationY + 10);
  
  const splitExplanation = doc.splitTextToSize(report.explanation, 180);
  doc.text(splitExplanation, 14, explanationY + 10 + (splitSummary.length * 5) + 5);

  // Recommendations
  const recY = explanationY + 10 + (splitSummary.length * 5) + (splitExplanation.length * 5) + 15;
  doc.setFillColor(240, 253, 250); // brand-50
  doc.setDrawColor(13, 148, 136);
  doc.rect(14, recY, 182, 30, 'FD');
  
  doc.setTextColor(13, 148, 136);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Professional Recommendations:', 20, recY + 10);
  
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const splitRecs = doc.splitTextToSize(report.recommendations, 170);
  doc.text(splitRecs, 20, recY + 18);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('This report is generated by SepCheck AI for preliminary screening purposes. Please consult a physical doctor immediately in case of emergencies.', 105, 285, { align: 'center' });

  doc.save(`SepCheck_Report_${patientProfile.full_name.replace(/\s+/g, '_')}_${report.id}.pdf`);
};
